### ISSUE TITLE
404 je okazis l' EPUB-n en retej'

### ISSUE THREAD

**Issue by equwal** [mihxil/profitulo#1]
https://meeuw.org/profitulo/profitulo.epub

(je l' esperant'!)

**Comment by mihxil** [comment]
Dank' prol virimark'. Miaos la solvoprov'.

**Comment by equwal** [comment]
> Dank' prol virimark'. Miaos la solvoprov'.

mivisendis je l' epub' perede retpoŝtaĵ'

**Comment by mihxil** [comment]
Dank al vi, sedas la prefer' pril rekonstruad' per propra skriptar'.
